FROM fedora:33

RUN dnf install -y --nodocs findutils procps which time curl zstd \
    && dnf clean all

RUN groupadd --system --gid 2001 main \
    && useradd --no-log-init --system --create-home --gid main --uid 1001 main

WORKDIR /home/main

USER main

COPY rebuild.sh rebuild.sh
COPY entrypoint.sh entrypoint.sh

ENTRYPOINT ./entrypoint.sh
